
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-kejagung-hpa
  namespace: ns-kejagung
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-kejagung
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15